spring:
  config:
    import: optional:classpath:application-secret.yml
  application:
    name: shopapp
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:shopapp}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}  # create, update, validate,...
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000
  rabbitmq:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_PORT:5672}
      username: ${RABBITMQ_USERNAME:guest}
      password: ${RABBITMQ_PASSWORD:guest}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:4200/auth/google/callback}"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
api:
  prefix: /api/v1
  admin-prefix: /api/v1/admin

bezkoder:
  jwtSecret: ${JWT_SECRET}
  refreshTokenSecret: ${REFRESH_TOKEN_SECRET}
  jwtExpirationMs: ${JWT_EXPIRATION_MS:1800000}               # default 30 phút
  refreshTokenExpirationMs: ${REFRESH_TOKEN_EXPIRATION_MS:604800000} # default 7 ngày
ghtk:
  token: ${GHTK_TOKEN}
vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  secret-key: ${VNPAY_SECRET_KEY}
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "${VNPAY_RETURN_URI:http://localhost:4200/payments/payment-callback}"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

server:
  port: ${SERVER_PORT:8081}
