spring:
  application:
    name: shopapp
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password: "minhthuan0107"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Có thể là create, create-drop, update, hoặc validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true   # Hiển thị các câu lệnh SQL trên console
        format_sql: true # Format SQL cho dễ đọc
  servlet:
    multipart:
      max-file-size: 10MB   # Kích thước tối đa của file upload
      max-request-size: 20MB # Kích thước tối đa của toàn bộ request
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: /api/v1
bezkoder:
  jwtSecret: "bXlzdXBlcnNlY3JldGtleWZvcmphdG9yZmVjb25kdGVzdGluZ2RhdGV0byh0aXQpZ29lc2NhcGVzY2F0Y2l0cm9yZ2VuZXQ="
  jwtExpirationMs: 86400000
vnpay:
  tmn-code: "XCB5GDBK"
  secret-key: "DZYDEFH0PJOUI3S0VBLHGBW0WUG6KH0V"
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "${VNPAY_RETURN_URI:http://localhost:4200/payments/payment-callback}"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
